name: news_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.2
  carousel_slider: ^5.1.2
  http: ^1.6.0
  # dart_rss: ^2.0.1
  provider: ^6.0.4
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.7
  dio: ^5.9.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.10.0
  logger: ^2.6.2
  equatable: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_localizations:
    sdk: flutter
  build_runner: ^2.11.1
  freezed: ^3.2.5
  json_serializable: ^6.12.0

flutter:
  generate: true

  uses-material-design: true
 
